interrogaciones/examen/ejercicio2/config/routes.rb
Rails.application.routes.draw do
  resources :trojans
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

interrogaciones/examen/ejercicio2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

interrogaciones/examen/ejercicio2/app/models/trojan.rb
class Trojan < ApplicationRecord
  validates :name, presence: true
end

interrogaciones/examen/ejercicio2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

interrogaciones/examen/ejercicio2/app/controllers/trojans_controller.rb
class TrojansController < ApplicationController
  before_action :set_trojan, only: [:show, :edit, :update, :destroy]

  # GET /trojans
  # GET /trojans.json
  def index
    @trojans = Trojan.all
  end

  # GET /trojans/1
  # GET /trojans/1.json
  def show
  end

  # GET /trojans/new
  def new
    @trojan = Trojan.new
  end

  # GET /trojans/1/edit
  def edit
  end

  # POST /trojans
  # POST /trojans.json
  def create
    @trojan = Trojan.new(trojan_params)

    respond_to do |format|
      if @trojan.save
        format.html do
          if request.xhr?
            render partial: 'created_successfully'
          else
            redirect_to @trojan, notice: 'Trojan was successfully created.'
          end
        end
        format.json { render :show, status: :created, location: @trojan }
      else
        format.html do
          if request.xhr?
            render partial: 'form', locals: { trojan: @trojan }
          else
            render :new
          end
        end
        format.json { render json: @trojan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trojans/1
  # PATCH/PUT /trojans/1.json
  def update
    respond_to do |format|
      if @trojan.update(trojan_params)
        format.html { redirect_to @trojan, notice: 'Trojan was successfully updated.' }
        format.json { render :show, status: :ok, location: @trojan }
      else
        format.html { render :edit }
        format.json { render json: @trojan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trojans/1
  # DELETE /trojans/1.json
  def destroy
    @trojan.destroy
    respond_to do |format|
      format.html { redirect_to trojans_url, notice: 'Trojan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trojan
      @trojan = Trojan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trojan_params
      params.require(:trojan).permit(:name)
    end
end

interrogaciones/examen/ejercicio2/app/helpers/application_helper.rb
module ApplicationHelper
end

interrogaciones/examen/ejercicio2/app/helpers/trojans_helper.rb
module TrojansHelper
end

interrogaciones/examen/ejercicio2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ejercicio2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

interrogaciones/examen/ejercicio2/app/views/trojans/_created_successfully.html.erb
<div class="alert">
  New trojan successfully created and ready for battle
</div>

interrogaciones/examen/ejercicio2/app/views/trojans/_form.html.erb
<%= form_for(trojan, remote: true, data: { type: :html }) do |f| %>
  <% if trojan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trojan.errors.count, "error") %> prohibited this trojan from being saved:</h2>

      <ul>
      <% trojan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

interrogaciones/examen/ejercicio2/app/views/trojans/edit.html.erb
<h1>Editing Trojan</h1>

<%= render 'form', trojan: @trojan %>

<%= link_to 'Show', @trojan %> |
<%= link_to 'Back', trojans_path %>

interrogaciones/examen/ejercicio2/app/views/trojans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trojans</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trojans.each do |trojan| %>
      <tr>
        <td><%= trojan.name %></td>
        <td><%= link_to 'Show', trojan %></td>
        <td><%= link_to 'Edit', edit_trojan_path(trojan) %></td>
        <td><%= link_to 'Destroy', trojan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trojan', new_trojan_path %>

interrogaciones/examen/ejercicio2/app/views/trojans/new.html.erb
<h1>New Trojan</h1>

<div id="new-trojan">
  <%= render 'form', trojan: @trojan %>
</div>

<%= link_to 'Back', trojans_path %>

interrogaciones/examen/ejercicio2/app/views/trojans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @trojan.name %>
</p>

<%= link_to 'Edit', edit_trojan_path(@trojan) %> |
<%= link_to 'Back', trojans_path %>