interrogaciones/examen/ejercicio3/config/routes.rb
Rails.application.routes.draw do
  resources :journal_entries
  namespace :api do
    resources :journal_entries, only: [:index, :create]
  end

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

interrogaciones/examen/ejercicio3/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

interrogaciones/examen/ejercicio3/app/models/journal_entry.rb
class JournalEntry < ApplicationRecord
  belongs_to :user
end

interrogaciones/examen/ejercicio3/app/models/user.rb
class User < ApplicationRecord
end

interrogaciones/examen/ejercicio3/app/controllers/api/api_controller.rb
module Api
  class ApiController < ActionController::Base
    include ActionController::HttpAuthentication::Token::ControllerMethods

    protected

    def authenticate
      authenticate_or_request_with_http_token do |token, options|
        @current_user = User.find_by(token: token)
      end
    end

  end
end

interrogaciones/examen/ejercicio3/app/controllers/api/journal_entries_controller.rb
module Api
  class JournalEntriesController < ApiController
    before_action :authenticate, only: [:create]

    def index
      render json: JournalEntryManager.new.get_feed
    end

    def create
      journal_entry = JournalEntry.new(journal_entry_params)
      if journal_entry.save
        render json: journal_entry, status: :created
      else
        render json: { errors: journal_entry.errors }, status: :unprocessable_entity
      end
    end

    private

    def journal_entry_params
      params.require(:journal_entry).permit(:text, :feeling, :timestamp, :position, :user_id)
    end
  end
end

interrogaciones/examen/ejercicio3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected

  def current_user
    User.first
  end
end

interrogaciones/examen/ejercicio3/app/controllers/journal_entries_controller.rb
class JournalEntriesController < ApplicationController
  before_action :set_journal_entry, only: [:show, :edit, :update, :destroy]

  # GET /journal_entries
  # GET /journal_entries.json
  def index
    @journal_entries = JournalEntriesService.new.get_all
  end

  # GET /journal_entries/1
  # GET /journal_entries/1.json
  def show
  end

  # GET /journal_entries/new
  def new
    @journal_entry = JournalEntry.new
  end

  # GET /journal_entries/1/edit
  def edit
  end

  # POST /journal_entries
  # POST /journal_entries.json
  def create
    journal_entry_response = JournalEntriesService.new.create(journal_entry_params, current_user)
    # dependiendo de la respuesta de la API, hay que detectar el caso de error
    if journal_entry_response.key?('errors')
      # no es necesario hacer esto de esta forma, pues la vista podría también prepararse para recibir la respuesta de la API
      # o bien construir algún otro wrapper para la misma (usar ActiveRecord aquí no tiene mucho sentido si vamos a usar la API)
      @journal_entry = JournalEntry.new(journal_entry_params)
      @journal_entry.errors.add(journal_entry_response.errors)
      render :new
    else
      @journal_entry = JournalEntry.new(journal_entry_response)
      redirect_to @journal_entry, notice: 'Journal entry was successfully created.'
    end
  end

  # PATCH/PUT /journal_entries/1
  # PATCH/PUT /journal_entries/1.json
  def update
    respond_to do |format|
      if @journal_entry.update(journal_entry_params)
        format.html { redirect_to @journal_entry, notice: 'Journal entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @journal_entry }
      else
        format.html { render :edit }
        format.json { render json: @journal_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journal_entries/1
  # DELETE /journal_entries/1.json
  def destroy
    @journal_entry.destroy
    respond_to do |format|
      format.html { redirect_to journal_entries_url, notice: 'Journal entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journal_entry
      @journal_entry = JournalEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def journal_entry_params
      params.require(:journal_entry).permit(:text, :feeling, :timestamp, :position, :user_id)
    end
end

interrogaciones/examen/ejercicio3/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

interrogaciones/examen/ejercicio3/app/helpers/api/journal_entries_helper.rb
module Api::JournalEntriesHelper
end

interrogaciones/examen/ejercicio3/app/helpers/application_helper.rb
module ApplicationHelper
end

interrogaciones/examen/ejercicio3/app/helpers/journal_entries_helper.rb
module JournalEntriesHelper
end

interrogaciones/examen/ejercicio3/app/helpers/users_helper.rb
module UsersHelper
end

interrogaciones/examen/ejercicio3/app/views/journal_entries/_form.html.erb
<%= form_for(journal_entry) do |f| %>
  <% if journal_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(journal_entry.errors.count, "error") %> prohibited this journal_entry from being saved:</h2>

      <ul>
      <% journal_entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>

  <div class="field">
    <%= f.label :feeling %>
    <%= f.text_field :feeling %>
  </div>

  <div class="field">
    <%= f.label :timestamp %>
    <%= f.datetime_select :timestamp %>
  </div>

  <div class="field">
    <%= f.label :position %>
    <%= f.text_field :position %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

interrogaciones/examen/ejercicio3/app/views/journal_entries/edit.html.erb
<h1>Editing Journal Entry</h1>

<%= render 'form', journal_entry: @journal_entry %>

<%= link_to 'Show', @journal_entry %> |
<%= link_to 'Back', journal_entries_path %>

interrogaciones/examen/ejercicio3/app/views/journal_entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Journal Entries</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Feeling</th>
      <th>Timestamp</th>
      <th>Position</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @journal_entries.each do |journal_entry| %>
      <tr>
        <td><%= journal_entry.text %></td>
        <td><%= journal_entry.feeling %></td>
        <td><%= journal_entry.timestamp %></td>
        <td><%= journal_entry.position %></td>
        <td><%= journal_entry.user %></td>
        <td><%= link_to 'Show', journal_entry %></td>
        <td><%= link_to 'Edit', edit_journal_entry_path(journal_entry) %></td>
        <td><%= link_to 'Destroy', journal_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Journal Entry', new_journal_entry_path %>

interrogaciones/examen/ejercicio3/app/views/journal_entries/new.html.erb
<h1>New Journal Entry</h1>

<%= render 'form', journal_entry: @journal_entry %>

<%= link_to 'Back', journal_entries_path %>

interrogaciones/examen/ejercicio3/app/views/journal_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @journal_entry.text %>
</p>

<p>
  <strong>Feeling:</strong>
  <%= @journal_entry.feeling %>
</p>

<p>
  <strong>Timestamp:</strong>
  <%= @journal_entry.timestamp %>
</p>

<p>
  <strong>Position:</strong>
  <%= @journal_entry.position %>
</p>

<p>
  <strong>User:</strong>
  <%= @journal_entry.user %>
</p>

<%= link_to 'Edit', edit_journal_entry_path(@journal_entry) %> |
<%= link_to 'Back', journal_entries_path %>

interrogaciones/examen/ejercicio3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ejercicio3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

interrogaciones/examen/ejercicio3/app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

interrogaciones/examen/ejercicio3/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

interrogaciones/examen/ejercicio3/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

interrogaciones/examen/ejercicio3/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

interrogaciones/examen/ejercicio3/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>